export const team_members = [
  {
    name: "Md Abdullah Al Safi",
    position: "CEO & Head Of Engineer",
    github: "https://github.com/shafidark",
    twitter: "https://twitter.com",
    linkedIn: "https://www.linkedin.com/in/md-abdullah-al-safi-659734170/",
    image: "/images/Shafi.jpg",
  },
  {
    name: "Mohammad Ali Reza",
    position: "CTO",
    github: "https://github.com/MohammadAReza",
    twitter: "https://twitter.com",
    linkedIn: "https://www.linkedin.com/in/mohammad-a-reza-4ba304193/",
    image: "/images/reza.jpg",
  },
  {
    name: "Shezan Mahmmud",
    position: "Lead Full Stack Developer",
    github: "https://github.com/shafidark",
    twitter: "https://twitter.com",
    linkedIn: "https://www.linkedin.com/in/md-abdullah-al-safi-659734170/",
    image: "/images/shezan.jpg",
  },
  {
    name: "Fiham",
    position: "SEO EXPERT",
    github: "https://github.com/shafidark",
    twitter: "https://twitter.com",
    linkedIn: "https://www.linkedin.com/in/md-abdullah-al-safi-659734170/",
    image: "/images/Fiham.jpg",
  },
  {
    name: "Ashad Peyash",
    position: "Marketing Expert",
    github: "https://github.com/MohammadAReza",
    twitter: "https://twitter.com",
    linkedIn: "https://www.linkedin.com/in/mohammad-a-reza-4ba304193/",
    image: "/images/peyash.jpg",
  },
  {
    name: "Tashid Shikto",
    position: "Lead Graphics Designer",
    github: "https://github.com/shafidark",
    twitter: "https://twitter.com",
    linkedIn: "https://www.linkedin.com/in/md-abdullah-al-safi-659734170/",
    image: "/images/sikto.jpg",
  },
];
